#!/bin/bash

if [ -f ../DATA/imdb/out.txt ]; then
    rm ../DATA/imdb/out.txt
fi

for run in 1
do
  echo "#########################################################################" >> ../DATA/imdb/out.txt
  echo "RUN $run" >> ../DATA/imdb/out.txt

  echo "OnlyStrong" >> ../DATA/imdb/out.txt
  cd REVIEW/OnlyStrong
  python train_model.py
  python test_model.py >> ../../../DATA/imdb/out.txt
  cd ../../
  cd SENTENCE/OnlyStrong
  python train_model.py
  python test_model.py >> ../../../DATA/imdb/out.txt
  cd ../../

  echo "#########################################################################" >> ../DATA/imdb/out.txt

  echo "WeaSL" >> ../DATA/imdb/out.txt
  cd MULTIRES/WeaSL
  python train_model.py
  python test_model.py >> ../../../DATA/imdb/out.txt
  cd ../../

  echo "#########################################################################" >> ../DATA/imdb/out.txt

  echo "Augment" >> ../DATA/imdb/out.txt
  cd MULTIRES/Augment
  python train_model.py
  python test_model.py >> ../../../DATA/imdb/out.txt
  cd ../../

  # echo "#########################################################################" >> ../DATA/imdb/out.txt
  #
  # echo "MIL" >> ../DATA/imdb/out.txt
  # cd MULTIRES/MIL
  # python train_model.py
  # python validate_model.py >> ../../../DATA/imdb/out.txt
  # python test_model.py >> ../../../DATA/imdb/out.txt
  # cd ../../
  #
  echo "#########################################################################" >> ../DATA/imdb/out.txt

  echo "ATTENTION" >> ../DATA/imdb/out.txt
  cd MULTIRES/Attention
  python train_model.py
  python validate_model.py >> ../../../DATA/imdb/out.txt
  python test_model.py >> ../../../DATA/imdb/out.txt
  cd ../../
done
